### default observation parameters needed for DREAMS simulation
object : configuration
alias : OBS
name : DREAMS_default_configuration
description : default parameters needed for the DREAMS simulation

packages :
- DREAMS

yamls :
- LFOA.yaml
- LFOA_SBIG.yaml

properties :
  airmass : 1.2
  declination : +30
  hour_angle : 0
  pupil_angle : 0
  dit : 30
  ndit : 1
  filter_name : K
  sky :
    bg_mag : 19.5
    filter_name : K

---

### default simulation parameters needed for a LFAO simulation
object : simulation
alias : SIM
name : LFAO_simulation_paramters
description : RC simulation paramters

properties :
  random :
    seed : 9001

  spectral :
    wave_min : 0.3
    wave_mid : 0.55
    wave_max : 1.0

  computing :
    preload_field_of_view : False
